### ISSUE TITLE
Define supported browsers?

### ISSUE THREAD

**Issue by weeman1337** [freifunk/meshviewer#51]
After https://github.com/freifunk/meshviewer/pull/46

Unfortunately Vite [doesn't support browserlist](https://github.com/vitejs/vite/discussions/6849). I would recommend NOT to use the workaround from the issue, because we will then pull in another not so great maintained dependency and add more complexity to the build configuration. Build configurations always start simple and end up to be monsters by adding quirks, workarounds and other crazy stuff. We shouldn't do that (again).

Instead we should use https://vitejs.dev/config/build-options.html#build-target It defaults to `modules`, means:
- Firefox >= 78
- Safari >= 14
- Chrome >= 87
- Edge >= 88

If the list is good, we can just close this issue.

**Comment by maurerle** [comment]
From my point of view, this list sounds good and covers more than 90% of devices.
https://browsersl.ist/#q=defaults%2C+Firefox+%3E%3D+78%2C+Safari+%3E%3D+14%2C+Chrome+%3E%3D+87%2C+Edge+%3E%3D+88&region=alt-eu

**Comment by MyIgel** [comment]
Defaults are fine (and if someone complains we can add additional support as needed) -> so i would vote for the default too @weeman1337

**Comment by weeman1337** [comment]
Then let's stick to the defaults....
