### ISSUE TITLE
add statistics filters to URL, so they survive page reloads

### ISSUE THREAD

**Issue by Djfe** [freifunk/meshviewer#84]
## Describe the solution you'd like
The filters on the statistics page should appear on the url, maybe with `#` or `?` after the actual URL or parsed by the server in between slashes `/`
This is useful when I create a selector, then reload the page or exit the browser to return later, that all filters are gone.

Also it allows for linking to filtered maps.

**Comment by maurerle** [comment]
duplicate of #70
